# Ładowanie Bibliotek

In [921]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso, RidgeCV, LassoCV
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler

sns.set()

# Import danych

In [922]:
df = pd.read_csv('fires.csv')
df_test = pd.read_csv('fires_test.csv')

# Czyszczenie danych

In [923]:
df

     X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain   area
0    3  5   mar  tue  88.1   25.7   67.6   3.8  14.9  38   2.7   0.0   0.00
1    3  4   aug  mon  91.5  145.4  608.2  10.7  10.3  74   2.2   0.0   0.00
2    7  4   aug  sun  94.8  108.3  647.1  17.0  16.4  47   1.3   0.0   1.56
3    9  9   feb  thu  84.2    6.8   26.6   7.7   6.7  79   3.1   0.0   0.00
4    7  5   mar  fri  86.2   26.2   94.3   5.1   8.2  51   6.7   0.0   0.00
..  .. ..   ...  ...   ...    ...    ...   ...   ...  ..   ...   ...    ...
462  1  2   aug  wed  92.1  111.2  654.1   9.6  16.6  47   0.9   0.0   0.00
463  4  3   sep  thu  92.9  137.0  706.4   9.2  27.7  24   2.2   0.0   0.00
464  7  5   sep  tue  91.0  129.5  692.6   7.0  20.7  37   2.2   0.0  17.20
465  2  4   aug  sun  91.6  181.3  613.0   7.6  20.9  50   2.2   0.0  16.00
466  1  2   sep  thu  92.9  137.0  706.4   9.2  21.5  15   0.9   0.0   0.00

[467 rows x 13 columns]

In [924]:
df.isnull().sum()

X        0
Y        0
month    0
day      0
FFMC     0
DMC      0
DC       0
ISI      0
temp     0
RH       0
wind     0
rain     0
area     0
dtype: int64

In [925]:
df.describe()

,X,Y,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area
count,467.000000,467.000000,467.000000,467.000000,467.000000,467.000000,467.000000,467.000000,467.000000,467.000000,467.000000
mean,4.674518,4.314775,90.530621,111.988651,550.702141,9.019058,18.808137,44.743041,4.041970,0.010278,13.148116
std,2.318301,1.243634,5.742648,64.921742,246.072255,4.641102,5.831719,16.529669,1.781315,0.097508,66.382225
min,1.000000,2.000000,18.700000,1.100000,7.900000,0.000000,2.200000,15.000000,0.900000,0.000000,0.000000
25%,3.000000,4.000000,90.200000,70.250000,440.300000,6.350000,15.450000,33.000000,2.700000,0.000000,0.000000
50%,4.000000,4.000000,91.600000,108.300000,664.200000,8.400000,19.200000,42.000000,4.000000,0.000000,0.410000
75%,7.000000,5.000000,92.850000,142.400000,714.100000,10.900000,22.800000,54.000000,5.150000,0.000000,6.330000
max,9.000000,9.000000,96.200000,291.300000,860.600000,56.100000,33.300000,100.000000,9.400000,1.400000,1090.840000

In [926]:
pd.set_option('display.max_columns', None)
df = pd.get_dummies(df, columns=['month', 'day'])
df

,X,Y,FFMC,DMC,DC,ISI,temp,RH,wind,rain,area,month_apr,month_aug,month_dec,month_feb,month_jan,month_jul,month_jun,month_mar,month_may,month_nov,month_oct,month_sep,day_fri,day_mon,day_sat,day_sun,day_thu,day_tue,day_wed
0,3,5,88.1,25.7,67.6,3.8,14.9,38,2.7,0.0,0.00,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False
1,3,4,91.5,145.4,608.2,10.7,10.3,74,2.2,0.0,0.00,False,True,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False
2,7,4,94.8,108.3,647.1,17.0,16.4,47,1.3,0.0,1.56,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
3,9,9,84.2,6.8,26.6,7.7,6.7,79,3.1,0.0,0.00,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False
4,7,5,86.2,26.2,94.3,5.1,8.2,51,6.7,0.0,0.00,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
462,1,2,92.1,111.2,654.1,9.6,16.6,47,0.9,0.0,0.00,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True
463,4,3,92.9,137.0,706.4,9.2,27.7,24,2.2,0.0,0.00,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False
464,7,5,91.0,129.5,692.6,7.0,20.7,37,2.2,0.0,17.20,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,True,False
465,2,4,91.6,181.3,613.0,7.6,20.9,50,2.2,0.0,16.00,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False
466,1,2,92.9,137.0,706.4,9.2,21.5,15,0.9,0.0,0.00,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False

In [927]:
df_test.head()

   X  Y month  day  FFMC    DMC     DC   ISI  temp  RH  wind  rain
0  7  5   oct  mon  91.7   48.5  696.1  11.1  16.1  44   4.0   0.0
1  2  2   aug  sat  93.5  139.4  594.2  20.3  22.9  31   7.2   0.0
2  7  5   sep  sat  92.5   88.0  698.6   7.1  17.8  51   7.2   0.0
3  8  5   aug  wed  93.1  157.3  666.7  13.5  26.8  25   3.1   0.0
4  1  3   aug  fri  95.9  158.0  633.6  11.3  32.4  27   2.2   0.0

In [928]:
df_test.isnull().sum()

X        0
Y        0
month    0
day      0
FFMC     0
DMC      0
DC       0
ISI      0
temp     0
RH       0
wind     0
rain     0
dtype: int64

In [929]:
df_test = pd.get_dummies(df_test, columns=['month', 'day'])
df_test

,X,Y,FFMC,DMC,DC,ISI,temp,RH,wind,rain,month_apr,month_aug,month_jul,month_mar,month_oct,month_sep,day_fri,day_mon,day_sat,day_sun,day_thu,day_tue,day_wed
0,7,5,91.7,48.5,696.1,11.1,16.1,44,4.0,0.0,False,False,False,False,True,False,False,True,False,False,False,False,False
1,2,2,93.5,139.4,594.2,20.3,22.9,31,7.2,0.0,False,True,False,False,False,False,False,False,True,False,False,False,False
2,7,5,92.5,88.0,698.6,7.1,17.8,51,7.2,0.0,False,False,False,False,False,True,False,False,True,False,False,False,False
3,8,5,93.1,157.3,666.7,13.5,26.8,25,3.1,0.0,False,True,False,False,False,False,False,False,False,False,False,False,True
4,1,3,95.9,158.0,633.6,11.3,32.4,27,2.2,0.0,False,True,False,False,False,False,True,False,False,False,False,False,False
5,2,4,93.6,235.1,723.1,10.1,20.9,66,4.9,0.0,False,True,False,False,False,False,False,False,False,True,False,False,False
6,6,5,90.1,37.6,83.7,7.2,12.4,54,3.6,0.0,False,False,False,True,False,False,False,False,False,True,False,False,False
7,6,5,81.5,9.1,55.2,2.7,5.8,54,5.8,0.0,True,False,False,False,False,False,False,False,False,False,True,False,False
8,4,5,91.7,33.3,77.5,9.0,17.2,26,4.5,0.0,False,False,False,True,False,False,True,False,False,False,False,False,False
9,6,5,87.2,15.1,36.9,7.1,10.2,45,5.8,0.0,False,False,False,True,False,False,False,True,False,False,False,False,False
10,3,3,92.2,102.3,751.5,8.4,24.2,27,3.1,0.0,False,False,False,False,False,True,False,False,True,False,False,False,False
11,3,4,90.2,18.5,41.1,7.3,11.2,41,5.4,0.0,False,False,False,True,False,False,False,False,False,False,False,False,True
12,3,4,91.7,35.8,80.8,7.8,15.2,27,4.9,0.0,False,False,False,True,False,False,False,False,True,False,False,False,False
13,1,2,93.5,149.3,728.6,8.1,25.3,36,3.6,0.0,False,False,False,False,False,True,False,False,False,True,False,False,False
14,4,4,89.7,90.0,704.4,4.8,17.8,64,1.3,0.0,False,False,False,False,False,True,False,False,False,True,False,False,False
15,5,4,92.8,119.0,783.5,7.5,21.6,28,6.3,0.0,False,False,False,False,False,True,False,False,False,False,True,False,False
16,4,5,90.2,99.6,631.2,6.3,21.4,33,3.1,0.0,False,True,False,False,False,False,False,False,False,True,False,False,False
17,8,6,90.7,194.1,643.0,6.8,21.3,41,3.6,0.0,False,True,False,False,False,False,False,False,False,False,True,False,False
18,2,4,91.0,166.9,752.6,7.1,25.9,41,3.6,0.0,False,True,False,False,False,False,True,False,False,False,False,False,False
19,5,4,91.8,78.5,724.3,9.2,19.1,38,2.7,0.0,False,False,False,False,False,True,False,True,False,False,False,False,False
20,4,4,90.6,43.7,686.9,6.7,18.4,25,3.1,0.0,False,False,False,False,True,False,False,False,True,False,False,False,False
21,3,4,93.1,157.3,666.7,13.5,21.7,40,0.4,0.0,False,True,False,False,False,False,False,False,False,False,False,False,True
22,2,5,90.8,84.7,376.6,5.6,23.8,51,1.8,0.0,False,False,True,False,False,False,False,False,True,False,False,False,False
23,1,5,90.9,126.5,686.5,7.0,21.0,42,2.2,0.0,False,False,False,False,False,True,False,True,False,False,False,False,False
24,7,4,91.2,124.4,795.3,8.5,21.5,28,4.5,0.0,False,False,False,False,False,True,False,False,True,False,False,False,False
25,4,5,92.9,137.0,706.4,9.2,21.5,15,0.9,0.0,False,False,False,False,False,True,False,False,False,False,True,False,False
26,9,4,92.3,92.1,442.1,9.8,22.8,27,4.5,0.0,False,False,True,False,False,False,False,True,False,False,False,False,False
27,5,4,95.1,141.3,605.8,17.7,26.4,34,3.6,0.0,False,True,False,False,False,False,False,False,False,False,False,True,False
28,6,3,91.6,138.1,621.7,6.3,18.9,41,3.1,0.0,False,True,False,False,False,False,False,False,False,False,True,False,False
29,1,4,91.0,129.5,692.6,7.0,21.7,38,2.2,0.0,False,False,False,False,False,True,False,False,False,False,False,True,False
30,4,3,94.5,139.4,689.1,20.0,28.9,29,4.9,0.0,False,True,False,False,False,False,False,False,False,False,False,False,True
31,6,4,90.8,41.9,89.4,7.9,13.3,42,0.9,0.0,False,False,False,True,False,False,False,False,True,False,False,False,False
32,3,4,92.6,46.5,691.8,8.8,20.6,24,5.4,0.0,False,False,False,False,True,False,False,False,False,True,False,False,False
33,9,4,91.6,104.2,474.9,9.0,25.3,39,0.9,0.0,False,False,True,False,False,False,False,False,True,False,False,False,False
34,4,3,92.5,122.0,789.7,10.2,17.3,45,4.0,0.0,False,False,False,False,False,True,True,False,False,False,False,False,False
35,6,3,88.0,17.2,43.5,3.8,15.2,51,2.7,0.0,True,False,False,False,False,False,False,False,False,False,False,False,True
36,5,4,93.7,101.3,458.8,11.9,19.3,39,7.2,0.0,False,False,True,False,False,False,False,False,False,False,False,False,True
37,4,4,87.2,23.9,64.7,4.1,11.8,35,1.8,0.0,False,False,False,True,False,False,False,True,False,False,False,False,False
38,2,2,92.4,117.9,668.0,12.2,19.6,33,5.4,0.0,False,False,False,False,False,True,True,False,False,False,False,False,False
39,8,6,91.9,111.7,770.3,6.5,15.7,51,2.2,0.0,False,False,False,False,False,True,False,True,False,False,False,False,False
40,8,6,92.3,88.8,440.9,8.5,17.1,67,3.6,0.0,False,False,True,False,False,False,False,False,False,False,False,True,False
41,7,4,90.9,126.5,686.5,7.0,19.4,48,1.3,0.0,False,False,False,False,False,True,False,True,False,False,False,False,False
42,6,4,95.2,131.7,578.8,10.4,20.3,41,4.0,0.0,False,True,False,False,False,False,False,False,False,False,True,False,False
43,3,4,93.4,17.3,28.3,9.9,8.9,35,8.0,0.0,False,False,False,True,False,False,False,False,False,False,False,False,True
44,2,4,87.9,84.8,725.1,3.7,21.8,34,2.2,0.0,False,False,False,False,False,True,False,False,False,False,False,False,True
45,4,3,91.6,108.4,764.0,6.2,9.8,86,1.8,0.0,False,False,False,False,False,True,False,True,False,False,False,False,False
46,8,8,91.7,191.4,635.9,7.8,26.2,36,4.5,0.0,False,True,False,False,False,False,False,False,False,False,False,False,True
47,2,4,93.4,15.0,25.6,11.4,15.2,19,7.6,0.0,False,False,False,True,False,False,False,False,False,False,False,True,False
48,4,3,93.7,101.3,423.4,14.7,26.1,45,4.0,0.0,False,False,True,False,False,False,False,False,False,True,False,False,False
49,7,5,96.1,181.1,671.2,14.3,27.3,63,4.9,6.4,False,True,False,False,False,False,False,False,False,False,False,True,False

In [930]:
df['area'] = np.log1p(df['area'])

In [931]:
df2 = df.drop(columns=[
    'day_mon', 'day_tue', 'day_wed', 'day_thu', 'day_fri', 'day_sat', 'day_sun',
    'month_jan', 'month_feb', 'month_mar', 'month_apr', 'month_may', 'month_jun', 
    'month_jul', 'month_aug', 'month_sep', 'month_oct', 'month_nov', 'month_dec'
])

# Budowanie modelu

In [932]:
X = df.drop('area', axis=1)
y = df['area']
X2 = df2.drop('area', axis=1)
y2 = df2['area']

In [933]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train2, X_test2, y_train2, y_test2 = train_test_split(X2, y2, test_size=0.2, random_state=42)

In [934]:
scaler_full = StandardScaler()
X_train_scaled = scaler_full.fit_transform(X_train)
X_test_scaled = scaler_full.transform(X_test)

scaler_reduced = StandardScaler()
X_train_scaled2 = scaler_reduced.fit_transform(X_train2)
X_test_scaled2 = scaler_reduced.transform(X_test2)

### Regresja Liniowa

In [935]:
lr_model = LinearRegression()
lr_model2 = LinearRegression()

lr_model.fit(X_train_scaled, y_train)
lr_model2.fit(X_train_scaled2, y_train2)

LinearRegression()

In [936]:
y_pred_lr = lr_model.predict(X_test_scaled)

In [937]:
rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))

In [938]:
rmse_lr

np.float64(1.4125078011706702)

In [939]:
lr_model.fit(X_train_scaled2, y_train2)

LinearRegression()

In [940]:
y_pred_lr2 = lr_model2.predict(X_test_scaled2)

In [941]:
rmse_lr2 = np.sqrt(mean_squared_error(y_test2, y_pred_lr2))

In [942]:
rmse_lr2

np.float64(1.4097625969337)

In [943]:
rmse_lr - rmse_lr2

np.float64(0.0027452042369702223)

### Ridge

In [944]:
ridge_model = Ridge(alpha=1.0)
ridge_model.fit(X_train_scaled, y_train)

ridge_model2 = Ridge(alpha=1.0)
ridge_model2.fit(X_train_scaled2, y_train2)

Ridge()

In [945]:
ridge_pred = ridge_model.predict(X_test_scaled)

In [946]:
rmse_ridge = np.sqrt(mean_squared_error(y_test, ridge_pred))

In [947]:
rmse_ridge

np.float64(1.4121945753415674)

In [948]:
ridge_pred_ridge2 = ridge_model2.predict(X_test_scaled2)

In [949]:
rmse_ridge2 = np.sqrt(mean_squared_error(y_test2, ridge_pred_ridge2))

In [950]:
rmse_ridge2

np.float64(1.4097236765465753)

In [951]:
rmse_ridge - rmse_ridge2

np.float64(0.0024708987949921823)

In [952]:
alphas_to_test = np.logspace(-4, 2, 100)

In [953]:
ridge_cv = RidgeCV(alphas=alphas_to_test, scoring='neg_mean_squared_error', cv=5)
ridge_cv.fit(X_train_scaled, y_train)


y_pred_ridge_tuned = ridge_cv.predict(X_test_scaled)
rmse_ridge_tuned = np.sqrt(mean_squared_error(y_test, y_pred_ridge_tuned))

In [954]:
rmse_ridge_tuned

np.float64(1.400280105586107)

In [955]:
ridge_cv2 = RidgeCV(alphas=alphas_to_test, cv=5)
ridge_cv2.fit(X_train_scaled2, y_train2)


y_pred_ridge2_tuned = ridge_cv2.predict(X_test_scaled2)
rmse_ridge2_tuned = np.sqrt(mean_squared_error(y_test2, y_pred_ridge2_tuned))

In [956]:
rmse_ridge2_tuned

np.float64(1.4094436245057629)

### Lasso

In [957]:
lasso_model = Lasso(alpha=0.1)
lasso_model.fit(X_train_scaled, y_train)

lasso_model2 = Lasso(alpha=0.1)
lasso_model2.fit(X_train_scaled2, y_train2)

Lasso(alpha=0.1)

In [958]:
y_pred_lasso = lasso_model.predict(X_test_scaled)

In [959]:
rmse_lasso = np.sqrt(mean_squared_error(y_test, y_pred_lasso))

In [960]:
rmse_lasso

np.float64(1.4032222501892238)

In [961]:
y_pred_lasso2 = lasso_model2.predict(X_test_scaled2)

In [962]:
rmse_lasso2 = np.sqrt(mean_squared_error(y_test2, y_pred_lasso2))

In [963]:
rmse_lasso2

np.float64(1.4263380692036345)

In [964]:
rmse_lasso - rmse_lasso2

np.float64(-0.023115819014410732)

In [965]:
lasso_cv = LassoCV(alphas=alphas_to_test, cv=5)
lasso_cv.fit(X_train_scaled, y_train)


y_pred_lasso_tuned = lasso_cv.predict(X_test_scaled)
rmse_lasso_tuned = np.sqrt(mean_squared_error(y_test, y_pred_lasso_tuned))

In [966]:
rmse_lasso_tuned

np.float64(1.4062326720575042)

In [967]:
lasso_cv2 = LassoCV(alphas=alphas_to_test, cv=5)
lasso_cv2.fit(X_train_scaled2, y_train2)


y_pred_lasso2_tuned = lasso_cv2.predict(X_test_scaled2)
rmse_lasso2_tuned = np.sqrt(mean_squared_error(y_test2, y_pred_lasso2_tuned))

In [968]:
rmse_lasso2_tuned

np.float64(1.426566934429613)

In [ ]:
models_info = {
    "Linear Full": {
        "rmse": rmse_lr,
        "model": lr_model,
        "columns": X.columns,
        "scaler": scaler_full
    },
    "Linear Reduced": {
        "rmse": rmse_lr2,
        "model": lr_model2,
        "columns": X2.columns,
        "scaler": scaler_reduced
    },
    "Ridge Full (Base)": {
        "rmse": rmse_ridge,
        "model": ridge_model,
        "columns": X.columns,
        "scaler": scaler_full
    },
    "Ridge Full (Tuned)": {
        "rmse": rmse_ridge_tuned,
        "model": ridge_cv,
        "columns": X.columns,
        "scaler": scaler_full
    },
    "Ridge Reduced (Base)": {
        "rmse": rmse_ridge2,
        "model": ridge_model2,
        "columns": X2.columns,
        "scaler": scaler_reduced
    },
    "Ridge Reduced (Tuned)": {
        "rmse": rmse_ridge2_tuned,
        "model": ridge_cv2,
        "columns": X2.columns,
        "scaler": scaler_reduced
    },
    "Lasso Full (Base)": {
        "rmse": rmse_lasso,
        "model": lasso_model,
        "columns": X.columns,
        "scaler": scaler_full
    },
    "Lasso Full (Tuned)": {
        "rmse": rmse_lasso_tuned,
        "model": lasso_cv,
        "columns": X.columns,
        "scaler": scaler_full
    },
    "Lasso Reduced (Base)": {
        "rmse": rmse_lasso2,
        "model": lasso_model2,
        "columns": X2.columns,
        "scaler": scaler_reduced
    },
    "Lasso Reduced (Tuned)": {
        "rmse": rmse_lasso2_tuned,
        "model": lasso_cv2,
        "columns": X2.columns,
        "scaler": scaler_reduced
    }
}

In [970]:
best_model_name = min(models_info, key=lambda k: models_info[k]["rmse"])
best_model_data = models_info[best_model_name]
best_rmse_value = best_model_data["rmse"]

print(f"Najlepszy model to: {best_model_name} z wynikiem RMSE: {best_rmse_value}")

Najlepszy model to: Ridge Full (Tuned) z wynikiem RMSE: 1.400280105586107

# Wyniki

In [971]:
X_final = df_test.reindex(columns=best_model_data["columns"], fill_value=0)
X_final_scaled = best_model_data["scaler"].transform(X_final)

In [972]:
final_preds_log = best_model_data["model"].predict(X_final_scaled)
final_preds_hectares = np.expm1(final_preds_log)

In [973]:
submission = pd.DataFrame({'area': final_preds_hectares})
submission.to_csv('f.csv', index=False)