# Biblioteki

In [506]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge, Lasso, RidgeCV, LassoCV
from sklearn.metrics import mean_squared_error
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer

# Import danych

In [507]:
df = pd.read_csv('crimes.csv', na_values='?')
df_test = pd.read_csv('crimes_test.csv', na_values='?')

# Czyszczenie danych

In [508]:
cols_to_drop = ['state', 'county', 'community', 'communityname', 'fold']

df = df.drop(columns=cols_to_drop, errors='ignore')
df_test = df_test.drop(columns=cols_to_drop, errors='ignore')

In [509]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1744 entries, 0 to 1743
Columns: 123 entries, population to ViolentCrimesPerPop
dtypes: float64(123)
memory usage: 1.6 MB

In [510]:
df = df.drop_duplicates()

In [511]:
df

,population,householdsize,racepctblack,racePctWhite,racePctAsian,racePctHisp,agePct12t21,agePct12t29,agePct16t24,agePct65up,...,LandArea,PopDens,PctUsePubTrans,PolicCars,PolicOperBudg,LemasPctPolicOnPatr,LemasGangUnitDeploy,LemasPctOfficDrugUn,PolicBudgPerPop,ViolentCrimesPerPop
0,0.03,0.78,0.01,0.31,0.34,1.00,0.46,0.57,0.36,0.39,...,0.01,0.44,0.11,NaN,NaN,NaN,NaN,0.00,NaN,0.62
1,0.00,1.00,0.00,0.67,0.00,1.00,0.71,0.63,0.44,0.33,...,0.01,0.25,0.08,NaN,NaN,NaN,NaN,0.00,NaN,0.13
2,0.03,0.24,0.02,0.88,0.06,0.20,0.42,0.44,0.35,0.64,...,0.04,0.16,0.01,NaN,NaN,NaN,NaN,0.00,NaN,0.24
3,0.02,0.49,0.05,0.77,0.14,0.37,0.36,0.44,0.27,0.31,...,0.03,0.17,0.10,NaN,NaN,NaN,NaN,0.00,NaN,0.16
4,0.08,0.39,0.14,0.88,0.02,0.01,0.39,0.47,0.29,0.46,...,0.06,0.26,0.09,0.02,0.02,0.67,0.0,1.00,0.15,0.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1739,0.05,0.41,0.14,0.76,0.32,0.09,0.50,0.72,0.59,0.42,...,0.06,0.16,0.44,NaN,NaN,NaN,NaN,0.00,NaN,0.26
1740,0.00,0.52,0.01,0.98,0.04,0.01,0.43,0.48,0.28,0.33,...,0.08,0.04,0.03,NaN,NaN,NaN,NaN,0.00,NaN,0.18
1741,0.40,0.56,0.09,0.64,0.06,0.94,0.48,0.52,0.32,0.31,...,0.39,0.16,0.10,0.21,0.07,0.78,1.0,0.64,0.09,0.33
1742,0.07,0.51,0.06,0.88,0.12,0.03,0.48,0.52,0.34,0.18,...,0.25,0.05,0.02,NaN,NaN,NaN,NaN,0.00,NaN,0.07
1743,0.01,0.27,0.02,0.96,0.08,0.02,0.31,0.52,0.29,0.29,...,0.02,0.17,0.16,NaN,NaN,NaN,NaN,0.00,NaN,0.03

In [512]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1744 entries, 0 to 1743
Columns: 123 entries, population to ViolentCrimesPerPop
dtypes: float64(123)
memory usage: 1.6 MB

In [513]:
len(df)

1744

In [514]:
for col in df.columns:
    if df[col].isnull().sum() > 0:
        print(f"{col}:")
        print(df[col].isnull().sum())

OtherPerCap:
1
LemasSwornFT:
1466
LemasSwFTPerPop:
1466
LemasSwFTFieldOps:
1466
LemasSwFTFieldPerPop:
1466
LemasTotalReq:
1466
LemasTotReqPerPop:
1466
PolicReqPerOffic:
1466
PolicPerPop:
1466
RacialMatchCommPol:
1466
PctPolicWhite:
1466
PctPolicBlack:
1466
PctPolicHisp:
1466
PctPolicAsian:
1466
PctPolicMinor:
1466
OfficAssgnDrugUnits:
1466
NumKindsDrugsSeiz:
1466
PolicAveOTWorked:
1466
PolicCars:
1466
PolicOperBudg:
1466
LemasPctPolicOnPatr:
1466
LemasGangUnitDeploy:
1466
PolicBudgPerPop:
1466

In [515]:
missing_cols = []
for col in df.columns:
    if df[col].isnull().sum()/len(df) * 100 > 30:
        print(f"{col}:")
        print(f'{round((df[col].isnull().sum()/len(df)*100), 3)}%')
        missing_cols.append(col)

LemasSwornFT:
84.06%
LemasSwFTPerPop:
84.06%
LemasSwFTFieldOps:
84.06%
LemasSwFTFieldPerPop:
84.06%
LemasTotalReq:
84.06%
LemasTotReqPerPop:
84.06%
PolicReqPerOffic:
84.06%
PolicPerPop:
84.06%
RacialMatchCommPol:
84.06%
PctPolicWhite:
84.06%
PctPolicBlack:
84.06%
PctPolicHisp:
84.06%
PctPolicAsian:
84.06%
PctPolicMinor:
84.06%
OfficAssgnDrugUnits:
84.06%
NumKindsDrugsSeiz:
84.06%
PolicAveOTWorked:
84.06%
PolicCars:
84.06%
PolicOperBudg:
84.06%
LemasPctPolicOnPatr:
84.06%
LemasGangUnitDeploy:
84.06%
PolicBudgPerPop:
84.06%

In [516]:
df = df.drop(columns=missing_cols)

In [517]:
df

,population,householdsize,racepctblack,racePctWhite,racePctAsian,racePctHisp,agePct12t21,agePct12t29,agePct16t24,agePct65up,...,PctForeignBorn,PctBornSameState,PctSameHouse85,PctSameCity85,PctSameState85,LandArea,PopDens,PctUsePubTrans,LemasPctOfficDrugUn,ViolentCrimesPerPop
0,0.03,0.78,0.01,0.31,0.34,1.00,0.46,0.57,0.36,0.39,...,1.00,0.46,0.41,0.72,0.73,0.01,0.44,0.11,0.00,0.62
1,0.00,1.00,0.00,0.67,0.00,1.00,0.71,0.63,0.44,0.33,...,0.78,0.65,0.70,0.84,0.77,0.01,0.25,0.08,0.00,0.13
2,0.03,0.24,0.02,0.88,0.06,0.20,0.42,0.44,0.35,0.64,...,0.10,0.47,0.28,0.43,0.54,0.04,0.16,0.01,0.00,0.24
3,0.02,0.49,0.05,0.77,0.14,0.37,0.36,0.44,0.27,0.31,...,0.40,0.49,0.61,0.68,0.71,0.03,0.17,0.10,0.00,0.16
4,0.08,0.39,0.14,0.88,0.02,0.01,0.39,0.47,0.29,0.46,...,0.01,0.75,0.57,0.85,0.82,0.06,0.26,0.09,1.00,0.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1739,0.05,0.41,0.14,0.76,0.32,0.09,0.50,0.72,0.59,0.42,...,0.13,0.28,0.23,0.22,0.00,0.06,0.16,0.44,0.00,0.26
1740,0.00,0.52,0.01,0.98,0.04,0.01,0.43,0.48,0.28,0.33,...,0.09,0.89,0.79,0.90,0.85,0.08,0.04,0.03,0.00,0.18
1741,0.40,0.56,0.09,0.64,0.06,0.94,0.48,0.52,0.32,0.31,...,0.15,0.77,0.51,0.73,0.79,0.39,0.16,0.10,0.64,0.33
1742,0.07,0.51,0.06,0.88,0.12,0.03,0.48,0.52,0.34,0.18,...,0.09,0.56,0.40,0.53,0.55,0.25,0.05,0.02,0.00,0.07
1743,0.01,0.27,0.02,0.96,0.08,0.02,0.31,0.52,0.29,0.29,...,0.08,0.69,0.40,0.61,0.61,0.02,0.17,0.16,0.00,0.03

In [518]:
medians = df['OtherPerCap'].median()
df['OtherPerCap'] = df['OtherPerCap'].fillna(medians)

In [519]:
for col in df.columns:
    if df[col].isnull().sum() > 0:
        print(f"{col}:")
        print(df[col].isnull().sum())

In [520]:
df

,population,householdsize,racepctblack,racePctWhite,racePctAsian,racePctHisp,agePct12t21,agePct12t29,agePct16t24,agePct65up,...,PctForeignBorn,PctBornSameState,PctSameHouse85,PctSameCity85,PctSameState85,LandArea,PopDens,PctUsePubTrans,LemasPctOfficDrugUn,ViolentCrimesPerPop
0,0.03,0.78,0.01,0.31,0.34,1.00,0.46,0.57,0.36,0.39,...,1.00,0.46,0.41,0.72,0.73,0.01,0.44,0.11,0.00,0.62
1,0.00,1.00,0.00,0.67,0.00,1.00,0.71,0.63,0.44,0.33,...,0.78,0.65,0.70,0.84,0.77,0.01,0.25,0.08,0.00,0.13
2,0.03,0.24,0.02,0.88,0.06,0.20,0.42,0.44,0.35,0.64,...,0.10,0.47,0.28,0.43,0.54,0.04,0.16,0.01,0.00,0.24
3,0.02,0.49,0.05,0.77,0.14,0.37,0.36,0.44,0.27,0.31,...,0.40,0.49,0.61,0.68,0.71,0.03,0.17,0.10,0.00,0.16
4,0.08,0.39,0.14,0.88,0.02,0.01,0.39,0.47,0.29,0.46,...,0.01,0.75,0.57,0.85,0.82,0.06,0.26,0.09,1.00,0.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1739,0.05,0.41,0.14,0.76,0.32,0.09,0.50,0.72,0.59,0.42,...,0.13,0.28,0.23,0.22,0.00,0.06,0.16,0.44,0.00,0.26
1740,0.00,0.52,0.01,0.98,0.04,0.01,0.43,0.48,0.28,0.33,...,0.09,0.89,0.79,0.90,0.85,0.08,0.04,0.03,0.00,0.18
1741,0.40,0.56,0.09,0.64,0.06,0.94,0.48,0.52,0.32,0.31,...,0.15,0.77,0.51,0.73,0.79,0.39,0.16,0.10,0.64,0.33
1742,0.07,0.51,0.06,0.88,0.12,0.03,0.48,0.52,0.34,0.18,...,0.09,0.56,0.40,0.53,0.55,0.25,0.05,0.02,0.00,0.07
1743,0.01,0.27,0.02,0.96,0.08,0.02,0.31,0.52,0.29,0.29,...,0.08,0.69,0.40,0.61,0.61,0.02,0.17,0.16,0.00,0.03

In [521]:
for col in df_test.columns:
    if df_test[col].isnull().sum() > 0:
        print(f"{col}:")
        print(df_test[col].isnull().sum())

LemasSwornFT:
209
LemasSwFTPerPop:
209
LemasSwFTFieldOps:
209
LemasSwFTFieldPerPop:
209
LemasTotalReq:
209
LemasTotReqPerPop:
209
PolicReqPerOffic:
209
PolicPerPop:
209
RacialMatchCommPol:
209
PctPolicWhite:
209
PctPolicBlack:
209
PctPolicHisp:
209
PctPolicAsian:
209
PctPolicMinor:
209
OfficAssgnDrugUnits:
209
NumKindsDrugsSeiz:
209
PolicAveOTWorked:
209
PolicCars:
209
PolicOperBudg:
209
LemasPctPolicOnPatr:
209
LemasGangUnitDeploy:
209
PolicBudgPerPop:
209

In [522]:
missing_cols_test = []
for col in df_test.columns:
    if df_test[col].isnull().sum()/len(df_test) * 100 > 30:
        print(f"{col}:")
        print(f'{round((df_test[col].isnull().sum()/len(df_test)*100), 3)}%')
        missing_cols_test.append(col)

LemasSwornFT:
83.6%
LemasSwFTPerPop:
83.6%
LemasSwFTFieldOps:
83.6%
LemasSwFTFieldPerPop:
83.6%
LemasTotalReq:
83.6%
LemasTotReqPerPop:
83.6%
PolicReqPerOffic:
83.6%
PolicPerPop:
83.6%
RacialMatchCommPol:
83.6%
PctPolicWhite:
83.6%
PctPolicBlack:
83.6%
PctPolicHisp:
83.6%
PctPolicAsian:
83.6%
PctPolicMinor:
83.6%
OfficAssgnDrugUnits:
83.6%
NumKindsDrugsSeiz:
83.6%
PolicAveOTWorked:
83.6%
PolicCars:
83.6%
PolicOperBudg:
83.6%
LemasPctPolicOnPatr:
83.6%
LemasGangUnitDeploy:
83.6%
PolicBudgPerPop:
83.6%

In [523]:
df_test = df_test.drop(columns=missing_cols_test)

In [524]:
df_test.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 100 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   population             250 non-null    float64
 1   householdsize          250 non-null    float64
 2   racepctblack           250 non-null    float64
 3   racePctWhite           250 non-null    float64
 4   racePctAsian           250 non-null    float64
 5   racePctHisp            250 non-null    float64
 6   agePct12t21            250 non-null    float64
 7   agePct12t29            250 non-null    float64
 8   agePct16t24            250 non-null    float64
 9   agePct65up             250 non-null    float64
 10  numbUrban              250 non-null    float64
 11  pctUrban               250 non-null    float64
 12  medIncome              250 non-null    float64
 13  pctWWage               250 non-null    float64
 14  pctWFarmSelf           250 non-null    float64
 15  pctWInvInc             250 non-null    float64
 16  pctWSocSec             250 non-null    float64
 17  pctWPubAsst            250 non-null    float64
 18  pctWRetire             250 non-null    float64
 19  medFamInc              250 non-null    float64
 20  perCapInc              250 non-null    float64
 21  whitePerCap            250 non-null    float64
 22  blackPerCap            250 non-null    float64
 23  indianPerCap           250 non-null    float64
 24  AsianPerCap            250 non-null    float64
 25  OtherPerCap            250 non-null    float64
 26  HispPerCap             250 non-null    float64
 27  NumUnderPov            250 non-null    float64
 28  PctPopUnderPov         250 non-null    float64
 29  PctLess9thGrade        250 non-null    float64
 30  PctNotHSGrad           250 non-null    float64
 31  PctBSorMore            250 non-null    float64
 32  PctUnemployed          250 non-null    float64
 33  PctEmploy              250 non-null    float64
 34  PctEmplManu            250 non-null    float64
 35  PctEmplProfServ        250 non-null    float64
 36  PctOccupManu           250 non-null    float64
 37  PctOccupMgmtProf       250 non-null    float64
 38  MalePctDivorce         250 non-null    float64
 39  MalePctNevMarr         250 non-null    float64
 40  FemalePctDiv           250 non-null    float64
 41  TotalPctDiv            250 non-null    float64
 42  PersPerFam             250 non-null    float64
 43  PctFam2Par             250 non-null    float64
 44  PctKids2Par            250 non-null    float64
 45  PctYoungKids2Par       250 non-null    float64
 46  PctTeen2Par            250 non-null    float64
 47  PctWorkMomYoungKids    250 non-null    float64
 48  PctWorkMom             250 non-null    float64
 49  NumIlleg               250 non-null    float64
 50  PctIlleg               250 non-null    float64
 51  NumImmig               250 non-null    float64
 52  PctImmigRecent         250 non-null    float64
 53  PctImmigRec5           250 non-null    float64
 54  PctImmigRec8           250 non-null    float64
 55  PctImmigRec10          250 non-null    float64
 56  PctRecentImmig         250 non-null    float64
 57  PctRecImmig5           250 non-null    float64
 58  PctRecImmig8           250 non-null    float64
 59  PctRecImmig10          250 non-null    float64
 60  PctSpeakEnglOnly       250 non-null    float64
 61  PctNotSpeakEnglWell    250 non-null    float64
 62  PctLargHouseFam        250 non-null    float64
 63  PctLargHouseOccup      250 non-null    float64
 64  PersPerOccupHous       250 non-null    float64
 65  PersPerOwnOccHous      250 non-null    float64
 66  PersPerRentOccHous     250 non-null    float64
 67  PctPersOwnOccup        250 non-null    float64
 68  PctPersDenseHous       250 non-null    float64
 69  PctHousLess3BR         250 non-null    float64
 70  MedNumBR               250 non-null    float64
 71  HousVacant             250 non-null    float64
 72  PctHousOccup           250 non-null    float64
 73  PctHousOwnOcc          250 non-null    float64
 74  PctVacantBoarded       250 non-null    float64
 75  PctVacMore6Mos         250 non-null    float64
 76  MedYrHousBuilt         250 non-null    float64
 77  PctHousNoPhone         250 non-null    float64
 78  PctWOFullPlumb         250 non-null    float64
 79  OwnOccLowQuart         250 non-null    float64
 80  OwnOccMedVal           250 non-null    float64
 81  OwnOccHiQuart          250 non-null    float64
 82  RentLowQ               250 non-null    float64
 83  RentMedian             250 non-null    float64
 84  RentHighQ              250 non-null    float64
 85  MedRent                250 non-null    float64
 86  MedRentPctHousInc      250 non-null    float64
 87  MedOwnCostPctInc       250 non-null    float64
 88  MedOwnCostPctIncNoMtg  250 non-null    float64
 89  NumInShelters          250 non-null    float64
 90  NumStreet              250 non-null    float64
 91  PctForeignBorn         250 non-null    float64
 92  PctBornSameState       250 non-null    float64
 93  PctSameHouse85         250 non-null    float64
 94  PctSameCity85          250 non-null    float64
 95  PctSameState85         250 non-null    float64
 96  LandArea               250 non-null    float64
 97  PopDens                250 non-null    float64
 98  PctUsePubTrans         250 non-null    float64
 99  LemasPctOfficDrugUn    250 non-null    float64
dtypes: float64(100)
memory usage: 195.4 KB

In [525]:
for col in df_test.columns:
    if df_test[col].isnull().sum() > 0:
        print(f"{col}:")
        print(df_test[col].isnull().sum())

# Budowanie modelu

In [526]:
X = df.drop('ViolentCrimesPerPop', axis=1)
y = df['ViolentCrimesPerPop']

In [527]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [528]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

X_test_csv_scaled = scaler.transform(df_test)

In [529]:
alphas_to_test = np.logspace(-4, 4, 100)

### Regresja liniowa

In [530]:
lr_model = LinearRegression()
lr_model.fit(X_train_scaled, y_train)

LinearRegression()

In [531]:
y_pred_lr = lr_model.predict(X_test_scaled)
rmse_lr = np.sqrt(mean_squared_error(y_test, y_pred_lr))
print(f"Regresja Liniowa RMSE: {rmse_lr}")

Regresja Liniowa RMSE: 0.13481814479834284

### Ridge

In [532]:
ridge_basic = Ridge(alpha=1.0)
ridge_basic.fit(X_train_scaled, y_train)

Ridge()

In [533]:
y_pred_ridge_basic = ridge_basic.predict(X_test_scaled)
rmse_ridge_basic = np.sqrt(mean_squared_error(y_test, y_pred_ridge_basic))
print(f"Ridge (bez tuningu) RMSE: {rmse_ridge_basic}")

Ridge (bez tuningu) RMSE: 0.1339998316105929

In [534]:
ridge_cv = RidgeCV(alphas=alphas_to_test, cv=5)
ridge_cv.fit(X_train_scaled, y_train)

RidgeCV(alphas=array([1.00000000e-04, 1.20450354e-04, 1.45082878e-04, 1.74752840e-04,
       2.10490414e-04, 2.53536449e-04, 3.05385551e-04, 3.67837977e-04,
       4.43062146e-04, 5.33669923e-04, 6.42807312e-04, 7.74263683e-04,
       9.32603347e-04, 1.12332403e-03, 1.35304777e-03, 1.62975083e-03,
       1.96304065e-03, 2.36448941e-03, 2.84803587e-03, 3.43046929e-03,
       4.13201240e-03, 4.97702356e-0...
       1.38488637e+02, 1.66810054e+02, 2.00923300e+02, 2.42012826e+02,
       2.91505306e+02, 3.51119173e+02, 4.22924287e+02, 5.09413801e+02,
       6.13590727e+02, 7.39072203e+02, 8.90215085e+02, 1.07226722e+03,
       1.29154967e+03, 1.55567614e+03, 1.87381742e+03, 2.25701972e+03,
       2.71858824e+03, 3.27454916e+03, 3.94420606e+03, 4.75081016e+03,
       5.72236766e+03, 6.89261210e+03, 8.30217568e+03, 1.00000000e+04]),
        cv=5)

In [535]:
y_pred_ridge_tuned = ridge_cv.predict(X_test_scaled)
rmse_ridge_tuned = np.sqrt(mean_squared_error(y_test, y_pred_ridge_tuned))

print(f"Ridge (z tuningiem, wybrane alpha: {ridge_cv.alpha_:.4f}) RMSE: {rmse_ridge_tuned}")

Ridge (z tuningiem, wybrane alpha: 200.9233) RMSE: 0.1353647950843912

### Lasso

In [536]:
lasso_basic = Lasso(alpha=1.0)
lasso_basic.fit(X_train_scaled, y_train)

Lasso()

In [537]:
y_pred_lasso_basic = lasso_basic.predict(X_test_scaled)
rmse_lasso_basic = np.sqrt(mean_squared_error(y_test, y_pred_lasso_basic))
print(f"Lasso (bez tuningu) RMSE: {rmse_lasso_basic}")

Lasso (bez tuningu) RMSE: 0.24080791825093653

In [538]:
lasso_cv = LassoCV(alphas=alphas_to_test, cv=5)
lasso_cv.fit(X_train_scaled, y_train)

/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.264e-03, tolerance: 6.287e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.717e-03, tolerance: 6.287e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.835e-02, tolerance: 6.287e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.245e-02, tolerance: 6.287e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 9.524e-03, tolerance: 6.287e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 7.333e-03, tolerance: 6.287e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.581e-02, tolerance: 6.287e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.987e-03, tolerance: 6.238e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.895e-02, tolerance: 6.238e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.132e-02, tolerance: 6.238e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.958e-02, tolerance: 6.238e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.418e-02, tolerance: 6.238e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.542e-02, tolerance: 6.049e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 4.747e-02, tolerance: 6.049e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.948e-02, tolerance: 6.049e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 8.023e-02, tolerance: 6.049e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 6.463e-03, tolerance: 5.876e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.804e-02, tolerance: 5.876e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.934e-02, tolerance: 5.876e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.791e-02, tolerance: 5.876e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.784e-02, tolerance: 5.876e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.831e-02, tolerance: 5.876e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.518e-02, tolerance: 5.486e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.955e-02, tolerance: 5.486e-03
  model = cd_fast.enet_coordinate_descent_gram(
/Users/mikolajkoszewski/venv_studia/.venv/lib/python3.14/site-packages/sklearn/linear_model/_coordinate_descent.py:701: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 3.877e-02, tolerance: 5.486e-03
  model = cd_fast.enet_coordinate_descent_gram(

LassoCV(alphas=array([1.00000000e-04, 1.20450354e-04, 1.45082878e-04, 1.74752840e-04,
       2.10490414e-04, 2.53536449e-04, 3.05385551e-04, 3.67837977e-04,
       4.43062146e-04, 5.33669923e-04, 6.42807312e-04, 7.74263683e-04,
       9.32603347e-04, 1.12332403e-03, 1.35304777e-03, 1.62975083e-03,
       1.96304065e-03, 2.36448941e-03, 2.84803587e-03, 3.43046929e-03,
       4.13201240e-03, 4.97702356e-0...
       1.38488637e+02, 1.66810054e+02, 2.00923300e+02, 2.42012826e+02,
       2.91505306e+02, 3.51119173e+02, 4.22924287e+02, 5.09413801e+02,
       6.13590727e+02, 7.39072203e+02, 8.90215085e+02, 1.07226722e+03,
       1.29154967e+03, 1.55567614e+03, 1.87381742e+03, 2.25701972e+03,
       2.71858824e+03, 3.27454916e+03, 3.94420606e+03, 4.75081016e+03,
       5.72236766e+03, 6.89261210e+03, 8.30217568e+03, 1.00000000e+04]),
        cv=5)

In [539]:
y_pred_lasso_tuned = lasso_cv.predict(X_test_scaled)
rmse_lasso_tuned = np.sqrt(mean_squared_error(y_test, y_pred_lasso_tuned))

print(f"Lasso (z tuningiem, wybrane alpha: {lasso_cv.alpha_:.4f}) RMSE: {rmse_lasso_tuned}")

Lasso (z tuningiem, wybrane alpha: 0.0041) RMSE: 0.13598066311073465

### Najlepszy model

In [540]:
models_info = {
    "Linear Regression": {"rmse": rmse_lr, "model": lr_model},
    "Ridge (bez tuningu)": {"rmse": rmse_ridge_basic, "model": ridge_basic},
    "Ridge (z tuningiem)": {"rmse": rmse_ridge_tuned, "model": ridge_cv},
    "Lasso (bez tuningu)": {"rmse": rmse_lasso_basic, "model": lasso_basic},
    "Lasso (z tuningiem)": {"rmse": rmse_lasso_tuned, "model": lasso_cv}
}

In [541]:
best_model_name = min(models_info, key=lambda k: models_info[k]["rmse"])
best_model = models_info[best_model_name]["model"]
best_rmse_value = models_info[best_model_name]["rmse"]

print(f"Najlepszy model to: {best_model_name} z wynikiem RMSE: {best_rmse_value}")

Najlepszy model to: Ridge (bez tuningu) z wynikiem RMSE: 0.1339998316105929

# Wyniki

In [542]:
final_predictions = best_model.predict(X_test_scaled)

In [543]:
submission = pd.DataFrame({'crimes': final_predictions})
submission.to_csv('c.csv', index=False)